[package]
name = "bevox"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
noise = "0.9"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rayon = "1.10"
ahash = "0.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
